config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #課題
  # get 'users/:id/followings', to: 'users#followings'
  # get 'users/:id/followers', to: 'users#followers'
  
  #アプリケーションで使用するテーブルを指定
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  #コールバック(保存前に処理を実行)
  before_save { self.email = self.email.downcase }
  
  validates :name, presence: true, length:{maximum:50}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length:{maximum:255},
                    format:{ with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  validates :address, length: { minimum: 3, maximum: 100 },
                      allow_blank: true, on: :update
                      
  validates :age, numericality: {
            only_integer: true, greater_than_or_equal_to: 1,
            less_than: 120 }, allow_blank: true, on: :update
            
  validates :remarks, length: { minimum: 2, maximum: 200 },
                      allow_blank: true, on: :update
                      
  #id一つに付き複数のデータと紐づく。
  has_many :microposts
  
  has_many :following_relationships, class_name: "Relationship",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
                                    
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy
  
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  has_many :favorites, dependent: :destroy
  
  has_many :favorite_posts, through: :favorites, source: :micropost
  
  #ユーザーを検索し、未フォローの場合はフォローを追加する
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end
  
  #フォローしているユーザーならば削除する
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end
  
  #ユーザーをフォローしているか確認
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update, :followings, :followers, :favorites]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  def new
    #初期化処理
    @user = User.new
  end
  
  def create
    @user = User.new(new_user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(edit_user_params)
      flash[:success] = "Updated Profile!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def followings
    @title = "followings_List"
    @users = @user.following_users
    render 'show_follower'
  end

  def followers
    @title = "followers_List"
    @users = @user.follower_users
    render 'show_follower'
  end

  def favorites
    @title = "favorite_posts"
    @favorites = @user.favorite_posts
    render 'show_favorite'
  end

  private
  
  def set_params
    @user = User.find(params[:id])
  end
  
  def correct_user
    redirect_to root_path if !current_user?(@user)
  end

  def new_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def edit_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                  :age, :address, :remarks)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
              html:{method: :delete},
              remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to (gravatar_for user, size:50), user %>
  <%= link_to user.name, user %>
</li>

app/views/users/_user_info.html.erb
<section class="user_info">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <p>
    <%= link_to "profile", @user %> |
    <%= link_to "followings", followings_user_path(@user) %> | 
    <%= link_to "followeres", followers_user_path(@user) %>
  </p>
</section>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>  <span class="label label-primary">required</span>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :email %>  <span class="label label-primary">required</span>
      <%= f.text_field :email, class: "form-control" %>
      
      <%= f.label :age %>  <span class="label label-default">from 1 to 120</span>
      <%= f.text_field :age, class: "form-control" %>
      
      <%= f.label :address %>  <span class="label label-default">100 to character</span>
      <%= f.text_field :address, class: "form-control" %>
      
      <%= f.label :remarks %>  <span class="label label-default">200 to character</span>
      <%= f.text_area :remarks, class: "form-control", rows: 5 %>
      
      <%# パスワード設定・暗号化(password_digest) %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
      
      <%# パスワード設定・暗号化(password_digest) %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %> 
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>

app/views/users/show_favorite.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %> (<%= @favorites.count %>)</h3>
    <ol class="microposts">
      <%= render @favorites %>
    </ol>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %> (<%= @users.count %>)</h3>
    <ol class="users">
      <%= render @users %>
    </ol>
  </div>
</div>